server:
  port: 8800
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.107:8700/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon-test
    api-b:
      path: /api-b/**
      serviceId: service-feign-test
