server:
  port: 8286

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.107:8700/eureka/
  # 驱动配置信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/quickapp?generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  second-datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/quickapp?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000
    password:
  thymeleaf:
    cache: false

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml