spring: 
  application:
  name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yang19950611/marks
          searchPaths: config/quickapp,config/eureka
          username:
          password:
    label: master

server:
  port: 8900


